server:
  port: 8082

spring:
  application:
    name: client-app

  # ==================== OAuth2 Resource Server 配置 ====================
  # 后端仅作为 Resource Server，校验前端传递的 JWT Bearer Token
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.local:9000

logging:
  level:
    com.example.appspringboot: DEBUG
    org.springframework.security: DEBUG

# ==================== 用户中心服务配置 ====================
user-service:
  url: http://localhost:8081  # user-service 地址
