server:
  port: 8082

spring:
  application:
    name: app-springboot

  # OAuth2 Client 配置 (直接与 auth-server 交互获取 Token)
  security:
    oauth2:
      client:
        registration:
          springboot-app:
            client-id: springboot-app
            client-secret: "Admin@123"
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            #重定向地址（前后端共用 client.a.local 域名）
            redirect-uri: "http://client.a.local:8082/login/oauth2/code/springboot-app"
            client-authentication-method: client_secret_basic
        provider:
          springboot-app:
            issuer-uri: http://auth.local:9000

logging:
  level:
    com.example.appspringboot: DEBUG
    org.springframework.security: DEBUG
