server:
  port: 8082

spring:
  application:
    name: app-springboot

  security:
    oauth2:
      client:
        registration:
          auth-server:
            client-id: springboot-app
            client-secret: Admin@123
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "http://client.a.local:8082/login/oauth2/code/auth-server"
            client-name: SpringBoot应用
        provider:
          auth-server:
            issuer-uri: http://auth.local:9000
            authorization-uri: http://auth.local:9000/oauth2/authorize
            token-uri: http://auth.local:9000/oauth2/token
            user-info-uri: http://auth.local:9000/userinfo
            user-name-attribute: username

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
